# Generated by Django 2.2.11 on 2020-08-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20200827_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(blank=True, to='facility.Service'),
        ),
    ]
