# Generated by Django 2.2.11 on 2020-08-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_auto_20200827_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING PAYMENT', 'PENDING PAYMENT'), ('PENDING FOR CANCELLATION', 'PENDING FOR CANCELLATION'), ('CANCELLED', 'CANCELLED')], default='SUCCESS', max_length=25),
        ),
    ]
