# Generated by Django 2.2.11 on 2020-03-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_auto_20200320_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
