# Generated by Django 2.2.11 on 2020-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_auto_20200827_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING PAYMENT', 'PENDING PAYMENT'), ('PENDING FOR CANCELLATION', 'PENDING FOR CANCELLATION'), ('CANCELLED', 'CANCELLED')], default='PENDING PAYMENT', max_length=25),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
