# Generated by Django 2.2.11 on 2020-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_auto_20200829_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(),
        ),
    ]
