# Generated by Django 2.2.11 on 2020-03-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_auto_20200321_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
