# Generated by Django 2.2.11 on 2020-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_auto_20200829_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='services',
            field=models.ManyToManyField(blank=True, to='facility.Service'),
        ),
    ]
