# Generated by Django 2.2.11 on 2020-03-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0007_auto_20200321_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING FOR CANCELLATION', 'PENDING FOR CANCELLATION'), ('CANCELLED', 'CANCELLED')], default='SUCCESS', max_length=25),
            preserve_default=False,
        ),
    ]
