# Generated by Django 2.2.11 on 2020-09-02 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_cart_total'),
        ('facility', '0007_facility_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('plate_num', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Reservation',
            new_name='FacilityReservation',
        ),
        migrations.CreateModel(
            name='VehicleReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING PAYMENT', 'PENDING PAYMENT'), ('PENDING FOR CANCELLATION', 'PENDING FOR CANCELLATION'), ('CANCELLED', 'CANCELLED')], default='PENDING PAYMENT', max_length=25)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.IntegerField()),
                ('cancellation_note', models.CharField(blank=True, max_length=300, null=True)),
                ('purpose', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('starting_place', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('num_passengers', models.IntegerField(default=1)),
                ('driver', models.CharField(max_length=100)),
                ('services', models.ManyToManyField(blank=True, to='facility.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
