# Generated by Django 2.2.11 on 2020-09-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_auto_20200902_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='isVehicle',
        ),
    ]
