# Generated by Django 2.2.11 on 2020-09-05 07:03

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0009_remove_facility_isvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='court.png', upload_to='facility'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='services',
            field=models.ManyToManyField(blank=True, to='facility.Service'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='court.png', upload_to='facility'),
        ),
    ]
