# Generated by Django 2.2.11 on 2020-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0009_auto_20200322_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(default='court.png', upload_to='facility'),
        ),
    ]
