# Generated by Django 2.2.11 on 2020-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0011_auto_20200905_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
