# Generated by Django 2.2.11 on 2020-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200320_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='student', max_length=50),
            preserve_default=False,
        ),
    ]
